author: xpm
module: xpmKit
github_url: https://github.com/xcode-project-manager/xpm
copyright: 'Copyright © 2018 Pedro Piñera. All rights reserved.'
readme: README.md
documentation: Guides/*.md
skip_undocumented: true
theme: fullwidth
xcodebuild_arguments: [-workspace, 'xpm.xcworkspace', -scheme, 'xpmKit']
sdk: macosx
clean: true
min_acl: internal
custom_categories:
  - name: App
    children:
      - Constants
  - name: Commands
    children:
      - Command
      - CommandRegistry
      - CommandsContext
      - CreateIssueCommand
      - DumpCommand
      - GenerateCommand
      - InitCommand
      - UpdateCommand
      - VersionCommand
      - DumpCommandError
      - InitCommandError
      - CommandCheckError
      - ArgumentParserError
  - name: Errors
    children:
      - ErrorHandler
      - FatalError
      - ErrorType
  - name: Extensions
    children:
      - AbsolutePath+Extras
      - ArgumentParserError+FatalError
      - String+Error
  - name: Generator
    children:
      - BuildPhaseGenerator
      - BuildPhaseGenerationError
      - ConfigGenerator
      - FileGenerator
      - GenerationOptions
      - GeneratorContext
      - ProjectFileElements
      - ProjectGenerator
      - ProjectGroups
      - TargetGenerator
      - WorkspaceGenerator
  - name: Graph Loader
    children:
      - Graph
      - GraphCircularDetector
      - GraphJSONInitiatable
      - GraphLoader
      - GraphLoaderCache
      - GraphLoaderContext
      - GraphLoadingError
      - GraphManifestLoader
      - GraphModuleLoader
      - GraphNode
      - TargetNode
      - PrecompiledNode
      - LibraryNode
      - FrameworkNode
      - GraphManifestLoaderError
      - GraphError
      - GraphModuleLoaderError
      - PrecompiledNodeError
      - GraphCircularDetectorNode
      - DependencyReference
  - name: Models
    children:
      - BuildConfiguration
      - BuildFiles
      - Target
      - Workspace
      - Scheme
      - Arguments
      - Project
      - Settings
      - Platform
      - BuildPhase
      - Product
      - BaseResourcesBuildFile
      - Configuration
      - BuildAction
      - CopyBuildPhase
      - CoreDataModelBuildFile
      - HeadersBuildFile
      - HeadersBuildPhase
      - ResourcesBuildFile
      - ResourcesBuildPhase
      - RunAction
      - ScriptBuildPhase
      - SourcesBuildFile
      - SourcesBuildPhase
      - TestAction
      - BuildFileError
      - CopyBuildFile
  - name: Protocols
    children:
      - XcodeRepresentable
  - name: Updater
    children:
      - SPUStandardUpdaterController
      - SPUStandardUpdateController+App
      - SPUUpdater+CommandLine
      - UpdateController
      - SPUCommandLineUserDriver
  - name: Utils
    children:
      - CommandCheck
      - Context
      - FileAggregator
      - FileHandler
      - Logger
      - Printer
      - ResourceLocator
      - ResourceLocatingError
      - Shell
      - Signals
      - ShellError
      - UnhandledError
  - name: Validator
    children:
      - GraphValidator
      - ProjectValidator
      - TargetValidator
